Add chart for basic web service.
uw-iti-app-platform/helm-charts pull request #1
Opened 2021-10-07 23:35 UTC by tomthorogood

Starter chart to build from, modeled after the existing identity-tom confguration in https://github.com/uwit-iam/gcp-k8/blob/main/dev/identity-tom.

Look for anything conspicuously incorrect (ignoring `unconfigured` values). 

`basic-web-service` would be overridden in the dependent configuration's `fullnameOverride` value. (e.g., `identity-tom`).

---

Default template output:

```yaml
---
# Source: basic-web-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: basic-web-service
  labels:
    app: basic-web-service
    helm.sh/chart: basic-web-service-0.1.0
    app.kubernetes.io/name: basic-web-service
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: basic-web-service
---
# Source: basic-web-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-web-service
  labels:
    helm.sh/chart: basic-web-service-0.1.0
    app.kubernetes.io/name: basic-web-service
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-web-service
  template:
    metadata:
      labels:
        app: basic-web-service
        app.kubernetes.io/name: basic-web-service
    spec:
      containers:
        - name: basic-web-service
          image: unconfigured  # {"$imagePolicy": "default:basic-web-service-policy"}
          envFrom:
            - configMapRef:
                name: basic-web-service
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          resources:
            {}
---
# Source: basic-web-service/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-web-service
  labels:
    helm.sh/chart: basic-web-service-0.1.0
    app.kubernetes.io/name: basic-web-service
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: basic-web-service
                port:
                  number: 80
---
# Source: basic-web-service/templates/deployment.yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: basic-web-service-policy
  namespace: default  # must be 'default' in MCI, even if app itself is not in default
spec:
  imageRepositoryRef:
    name: basic-web-service-gcr
  filterTags:
    pattern: '^unconfigured\.(?P<ts>[0-9\.]+)\.v.+$'
    extract: '$ts'
  policy:
    alphabetical:
      order: asc
---
# Source: basic-web-service/templates/deployment.yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: basic-web-service-gcr
  namespace: default  # must be 'default' in MCI, even if app itself is not in default
spec:
  image: gcr.io//basic-web-service
  interval: 5m0s
  secretRef:
    name: flux-mci-registry-credential
---
# Source: basic-web-service/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: basic-web-service-test-connection
  labels:
    helm.sh/chart: basic-web-service-0.1.0
    app.kubernetes.io/name: basic-web-service
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['basic-web-service:80']
  restartPolicy: Never
```

2021-10-18 19:15 UTC, EricHorst commented on basic-web-service/templates/deployment.yaml
> +          image: unconfigured  # {"$imagePolicy": "default:{{ $appName }}-policy"}
No worries, I feel like we were all juggling a lot last week. Maybe this week will be better.

The chart should render on its own and not have any knowledge of image automation that will be used later.
At the line indicated it should be templated something like:
`image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"`

There should be no Flux comment on the image: line. The ImagePolicy and ImageRepository should be removed from the chart.

2021-11-18 21:04 UTC, silby requested changes
here's a first pass of stuff I don't get or think I know what should change. Taking this chart in isolation and comparing a bit to what IST's existing k8s config looks like.

2021-11-18 22:04 UTC, tomthorogood commented on basic-web-service/templates/NOTES.txt
> +1. Get the application URL by running these commands:
This was autogenerated, I don't know the answer. It can probably be removed.

2021-11-18 22:05 UTC, tomthorogood commented on basic-web-service/templates/hpa.yaml
> +kind: HorizontalPodAutoscaler
We don't use this, but in his demo erich recommended keeping this even though it's not needed now, that way ~if~ when we do need it, all we have to do is change it to `enabled`

2021-11-18 22:06 UTC, tomthorogood commented on basic-web-service/templates/_helpers.tpl
> +{{- end }}
I don't really know what this does, I'm not well-versed enough in kubernetes. I was just extracting to make a chart that will work for the apps we use in IAM as a first iteration, because the scope we agreed was that i would migrate one of our apps onto this chart.

2021-11-18 22:07 UTC, tomthorogood commented on basic-web-service/templates/deployment.yaml
> +              path: /status
Ok. FWIW, I wanted to be opinionated because we should be migrating away from `/health` as an endpoint name, which is what many things use. But I'm ok extracting that.

2021-11-18 22:08 UTC, tomthorogood commented on basic-web-service/templates/_helpers.tpl
> +{{- end }}
however, I don't know if this helper function is used. all of those were autogenerated.

2021-11-18 22:12 UTC, EricHorst commented on basic-web-service/templates/hpa.yaml
> +kind: HorizontalPodAutoscaler
I'd agree, don't pull out usable code that will just need to go back in at some point. It's a conditional so doesn't have to be enabled except where needed. Hopefully it'll be useful soon too.

2021-11-18 22:15 UTC, EricHorst commented on basic-web-service/templates/_helpers.tpl
> +{{- end }}
I'd suggest being thoughtful in _helpers.tpl which is all Helm std helpers and favoring keeping over removing. There are good security reasons for having service account flexibility.

2021-11-18 22:18 UTC, EricHorst commented on basic-web-service/templates/_helpers.tpl
> +{{- end }}
The new recommended standard is using `app.kubernetes.io/name:` as the label and selector for an app, vs older standards like `name:` or `app:`. The goal in name qualifiers is avoiding label conflicts. I suggest standard.

And again, I'd favor not making structural changes to the generated template and helpers without good reasons.

2021-11-18 23:00 UTC, silby commented on basic-web-service/templates/_helpers.tpl
> +{{- end }}
yeah but the helper is seemingly unused? I don't like seeing unused code around (yagni) but I suppose I also don't know what a service account is for.

2021-11-18 23:03 UTC, silby commented on basic-web-service/templates/deployment.yaml
> +              path: /status
Yeah an opinionated default is good and fewer knobs is also good so that's in tension. But this comment is a case of me thinking ahead to being able to slotting IST's existing apps into what we build here.

2021-11-18 23:03 UTC, silby commented on basic-web-service/templates/hpa.yaml
> +kind: HorizontalPodAutoscaler
Sure.

2021-11-18 23:46 UTC, silby commented on basic-web-service/templates/_helpers.tpl
> +{{- end }}
looks like `selectorLabels` is used to label the generated `Deployment` and select it from the generated `Service`. I'm just not certain from context why there's both an `app` label and an `app.kubernetes.io/name` label.

I also can't really tell what the function of `nameOverride` and `fullnameOverride` are or why you'd set them in your `values`. All of this can be ignored for the time being. Contra Eric, my bias when starting with an example is to delete everything I don't understand and add it back when I understand it, but it's all the same to me for now because I realize we should just merge this and get to a starting point so we can iterate on the details.

2021-11-18 23:46 UTC, silby commented
Overall this looks like a good starting point and I think I can start to see where knobs would go for IST's applications.

2021-11-19 00:05 UTC, tomthorogood commented on basic-web-service/templates/_helpers.tpl
> +{{- end }}
evan's right that this isn't used (and currently wrong, because I renamed the chart, but not all the values in helper, when I first started and didn't like my first choice of name.) I don't like seeing unused stuff either, but I kept a lot in this case because 

Since this stuff is autogenerated, it's pretty easy to re-kindle if it needed, all we have to do is run `helm create <chart-name>` in a new context and we can get all of them back.  Maybe the same can be said for the autoscaler config elsewhere discussed.

2021-11-19 00:06 UTC, tomthorogood commented on basic-web-service/templates/deployment.yaml
> +  {{- toYaml .Values.resources | nindent 4 }}
yes, this was a find and replace where i forgot the critical "replace" step. (or, more accurately, a copy-paste without an update). good eye.

2021-11-19 02:32 UTC, EricHorst commented on basic-web-service/templates/_helpers.tpl
> +{{- end }}
Thanks for drawing my attention to selectorLabels. We should not have both an app label and an app.kubernetes.io/name label. I'll comment elsewhere.

nameOverride and fullnameOverride are Helm-isms. I can't tell you why except that I believe there are some Helm default behaviours where the chart name is used unless overridden.

The only concern I have about stripping down is that this isn't so much an example chart as it is a functional skeleton that implements all the Helm style standards. Some of those are for good reasons and some may be just style.

2021-11-19 02:38 UTC, EricHorst commented on basic-web-service/templates/deployment.yaml
> +        {{- include "web-service.selectorLabels" . | nindent 8 }}
The `web-service.selectorLabels` should be removed everywhere since the selector labels are being hardcoded in the line above.

2021-11-19 02:39 UTC, EricHorst commented on basic-web-service/templates/deployment.yaml
> +      app: {{ $appName }}
Hardcoding the selector labels is fine, but should use the standard of `app.kubernetes.io/name: {{ $appname }}`

2021-11-19 15:25 UTC, tomthorogood commented on basic-web-service/templates/_helpers.tpl
> +{{- end }}
The override thing makes sense to me, otherwise every app generated from the cart is using the chart name. I don't understand `fullname` vs just `name` tho

2021-11-19 17:51 UTC, tomthorogood commented on basic-web-service/templates/deployment.yaml
> +      app: {{ $appName }}
I will make this change in a future commit. I started down this path but wanted to understand what I'm doing and . . . don't, yet.  So, I'd like to get something functional first, and then grok the finer details to bring it up to standard.

2021-11-19 17:52 UTC, tomthorogood commented on basic-web-service/templates/_helpers.tpl
> +{{- end }}
oh wait, no, i don't understand the overrides after all. i forgot that `app.name` is here; maybe I added app.name because it made more sense, but was afraid to remove the other values because they were used in helpers? I don't remember, it's been a while.

2021-11-19 18:03 UTC, tomthorogood commented on basic-web-service/templates/deployment.yaml
> +      app: {{ $appName }}
https://github.com/uw-iti-app-platform/helm-charts/issues/2

2021-11-19 19:54 UTC, tomthorogood commented
I have updated this repo and also created a [gist](https://gist.github.com/tomthorogood/e7f018b5093c72e01c7352ba394a3157) that shows: 

- The `values.yaml` that would configure `identity-tom` as it is today
- The resulting identity-tom.yml that would be applied (deployed? whatever) to the cluster.

I haven't tried actually deploying this configuration yet, but while I do that, I figured I could let y'all take a look while I find bugs.

2021-11-19 19:56 UTC, tomthorogood commented
Closes #2

2021-11-20 00:54 UTC, EricHorst reviewed
Other needs:

1. Without autoscaling, as a standard will want default of 2 replicas. So probably want logic to default to 2 unless autoscaling is enabled or if a different value is explicitly specified in values.
2. Also, as a standard will want pod anti-affinity so any replicas will land on different nodes. As it stands now, affinity is set in values. But the syntax for affinity is gross and it isn't nice to make every dev do their own affinity in values. So I suggest adding the standard (anti-) affinity clause to the deployment.
3. The env variables in config map is good way to do it. But there may be cases where some of those values are sensitive, ie if any are credentials, etc. One way is to just make sure deployers are very clear about how to handle secrets vs non-secrets. Another way is to consider sourcing the whole ConfigMap from Vault via an ExternalSecret, not from values.
4. Documentation should be clear that any secrets listed in `environmentSecrets:` need to be deployed as ExternalSecrets alongside the HelmRelease resource.

2021-11-20 00:54 UTC, EricHorst commented on basic-web-service/templates/service.yaml
> +    - port: 80
port: should be `{{ .Values.service.port }}` to agree with what the Ingress is targetting.

2021-11-22 18:04 UTC, silby requested changes
customize the `description` in Chart.yaml and then lgtm

2021-11-24 20:01 UTC, silby approved these changes

2021-11-29 21:36 UTC, merged